config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  # get 'users/new'
  root 'static_pages#home'
  # changed the below in 5.3.2 to follow the model below the comments
  # get 'static_pages/home'
  # get 'static_pages/help'
  # get  'static_pages/about'
  # get  'static_pages/contact'
  get '/help', to: 'static_pages#help' #,  # as:'helf'  use this to make an alternative name for the path
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do #pg 855 
    member do
      get :following, :followers
    end
  end

  # this is the other possibility that gets the url without the id
  # resources :users do
  #   collection do
  #     get :tigers
  #   end
  # end
  # 
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update] #pg 680
  resources :microposts, only: [:create, :destroy] #pg 758
  resources :relationships, only: [:create, :destroy] #pg 861

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'application#hello'
end

app/views/shared/_default_home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
<h2>
This is the home page for the
<a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %> </div>
<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"), "https://rubyonrails.org/" %>
<%# <%= link_to image_tag("kitten.jpg", alt: "Rails logo", width: "200"), "https://rubyonrails.org/" %> 

app/views/shared/_error_messages.html.erb
<%# <% if @user.errors.any? %> 
 <% if object.errors.any? %>
    <div id="error_explanation">
    <div class="alert alert-danger">
    <%# The form contains <%= pluralize(@user.errors.count, "error") %>
    The form contains <%= pluralize(object.errors.count, "error") %>.
    <%# pluaralise basically says whether there is a single or multiple errors see pg 403 %>
    </div>
    <ul>
        <%# <% @user.errors.full_messages.each do |msg| %> 
        <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li> <% end %>
    </ul>
    </div> 
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %> 
    <ol class="microposts">
        <%= render @feed_items %> 
        <%# Here Rails knows to call the micropost partial because each element of @feed_items has class Micropost.
         This causes Rails to look for a partial with the corresponding name in the views directory of the given resource: app/views/microposts/_micropost.html.erb %>
    </ol>
    <%= will_paginate @feed_items, params: { controller: :static_pages, action: :home } %> 
     <%#see page 780 for this explanation on the above  %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost, local: true) do |f| %> 
    <%= render 'shared/error_messages', object: f.object %> 
    <%# the line above uses object: f.object to pass the object whether its a user or micropost to the error messages partial see pg 766 %>
    <div class="field">
        <%= f.text_area :content, placeholder: "Compose new micropost..." %> 
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %> 
    <span class="image">
        <%= f.file_field :image, accept: "image/jpeg,image/gif,image/png" %>
    </span>
<% end %>

<script type="text/javascript"> 
 $("#micropost_image").bind("change", function() {
    const size_in_megabytes = this.files[0].size/1024/1024; 
    if (size_in_megabytes > 5) {
        alert("Maximum file size is 5MB. Please choose a smaller file.");
        $("#micropost_image").val("");
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %> 
<div class="stats">
    <a href="<%= following_user_path(@user) %>"> 
        <strong id="following" class="stat">
            <%= @user.following.count %> 
        </strong>
        following
    </a>
<a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat"> 
        <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_home.html.erb
 <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %> 
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %> 
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
       <%= render 'shared/feed' %> 
    </div>
  </div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>